defmodule LLMDB.Application do
  @moduledoc """
  OTP Application for LLMDB.

  Automatically loads the pre-built snapshot on application start.
  The snapshot is generated by `mix llm_db.build` and packaged
  with the release.
  """

  use Application

  @impl true
  def start(_type, _args) do
    # Ensure modality atoms exist before loading snapshot
    _ = LLMDB.Generated.ValidModalities.list()

    case LLMDB.load() do
      {:ok, _snapshot} ->
        {:ok, self()}

      {:error, reason} ->
        {:error, reason}
    end
  end
end
